### PR TITLE
blog: getting started contributing

### PR DESCRIPTION
**Pull request by SanyaKochhar**

### CODE REVIEW

**Comment by SanyaKochhar** [comment]
@flynnduism I was wondering if you could help me fix two things:
1. I've added the octocat emoji to the last paragraph using a png but it's creating a new line after itself: https://deploy-preview-32--openservicemesh.netlify.app/blog/getting-started-contributing/
2. Is it possible to reduce the spacing between each title and paragraph?
image. Not super necessary if it's not possible but a nice to have!

**Review by bridgetkromhout — APPROVED** [review]
LGTM! Let's get this out as soon as we're happy with the formatting.

**Comment by flynnduism** [comment]
@SanyaKochhar I've tweaked how images can be aligned in blog posts to get the result you want (using the [figure method](https://gohugo.io/content-management/shortcodes/#figure) which allows easier alignment / sizing in markdown).

Screen Shot 2021-06-29 at 1 09 10 PM


Reduced the spacing between `h3` and `p` also. Hope that all looks ok now.

**Comment by SanyaKochhar** [comment]
@flynnduism this looks perfect, thanks!

**Review by bridgetkromhout — APPROVED** [review]
Looks great!

**Pull request merged**
